---
- name: Set resource quotas for a Kubernetes cluster for a namespace
  hosts: localhost
  gather_facts: false
  vars:
    ns: "{{ ansible_eda.event.resource.metadata.name }}"
    requests_cpu: '2'
    limits_cpu: '3'
    requests_memory: '5Gi'
    limits_memory: '10Gi'

  tasks:
    - name: Get the namespace
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
        name: "{{ ns }}"
      register: ns_info

    - name: Set resource quotas if the namespace does not have an annotation marking to skip
      when: ns_info.resources[0].metadata.annotations['skip-resource-quota'] is not defined
      kubernetes.core.k8s:
        api_version: v1
        kind: ResourceQuota
        namespace: "{{ ns }}"
        name: resource-quota
        state: present
        definition:
          spec:
            hard:
              "limits.cpu": "{{ limits_cpu }}"
              "limits.memory": "{{ limits_memory }}"
              "requests.cpu": "{{ requests_cpu }}"
              "requests.memory": "{{ requests_memory }}"

